import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const root=process.env.STUDIO_URL||'http://127.0.0.1:8011';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
try{
  await page.goto(root);
  const demo=page.getByRole('button',{name:'体验示例课堂'});
  if(await demo.count())await demo.click();
  await page.getByRole('heading',{name:'水的三态',exact:true}).waitFor();
  await page.getByLabel('声音模式').selectOption('silent');
  await page.getByRole('button',{name:'开始讲课',exact:true}).click();
  await page.getByText('正在讲课',{exact:true}).waitFor();
  await page.getByLabel('下一页').click();
  await page.getByRole('heading',{name:'熔化与凝固',exact:true}).waitFor();
  await page.getByLabel('课堂问题').fill('蒸发是什么？');
  await page.getByLabel('发送问题').click();
  await page.locator('.message-body').filter({hasText:'根据已审核的课程资料：'}).waitFor();
  await page.getByText('已暂停',{exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'熔化与凝固',exact:true}).count(),1);
  await page.screenshot({path:'test-results/classroom-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'继续讲课',exact:true}).click();
  await page.getByText('正在讲课',{exact:true}).waitFor();
  await page.getByRole('button',{name:'教学知识库',exact:true}).click();
  await page.getByText('示例讲义 · 水的三态',{exact:true}).first().waitFor();
  await page.getByRole('button',{name:'课程与课件',exact:true}).click();
  await page.getByRole('button',{name:'编辑 / 查看'}).first().click();
  await page.getByRole('link',{name:'导出 PPTX'}).waitFor();
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'导出 PPTX'}).click()]);
  assert.match(download.suggestedFilename(),/\.pptx$/);
  await download.saveAs('test-results/course-export.pptx');
  await page.getByRole('button',{name:'教师与素材',exact:true}).click();
  await page.getByRole('button',{name:'保存档案'}).waitFor();
  await page.getByRole('button',{name:'服务与部署',exact:true}).click();
  await page.getByRole('heading',{name:'本地业务，云端模型'}).waitFor();
  await page.getByRole('button',{name:'互动课堂',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'恢复课堂'}).click();
  await page.getByRole('heading',{name:'熔化与凝固',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/classroom-mobile.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
  assert.equal(overflow,false,'mobile horizontal overflow');
  assert.deepEqual(errors,[],'browser console errors');
  console.log('UI PASS: lecture, interruption, resume, navigation, export, persisted progress, mobile layout');
}finally{await browser.close();}
